### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by TheCodedOne** [Diluv/MMD-Client#1]
- [ ] Download Mods/Modpacks from the server

- [ ] Generate Server Zips from Modpacks

- [ ] Export Modpack Zip

- [ ] Optional Install Files

- [ ] Custom Themes

- [ ] Notifications for file/project approval/rejection
